// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmfvXQ5kISTOpnGYhyqsJSlye7xcCn1no',
    appId: '1:488342117062:web:b299353a64f01e986315c7',
    messagingSenderId: '488342117062',
    projectId: 'muj-olx',
    authDomain: 'muj-olx.firebaseapp.com',
    storageBucket: 'muj-olx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY_-VsnFl-yu2kR-mWy0ent0t6j---lRY',
    appId: '1:488342117062:android:55c2c218c1b34b096315c7',
    messagingSenderId: '488342117062',
    projectId: 'muj-olx',
    storageBucket: 'muj-olx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_VzKgiHy2Zq0m5ZqcoPF2Cc_H0arvN-c',
    appId: '1:488342117062:ios:8e2c728542c72b996315c7',
    messagingSenderId: '488342117062',
    projectId: 'muj-olx',
    storageBucket: 'muj-olx.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_VzKgiHy2Zq0m5ZqcoPF2Cc_H0arvN-c',
    appId: '1:488342117062:ios:8e2c728542c72b996315c7',
    messagingSenderId: '488342117062',
    projectId: 'muj-olx',
    storageBucket: 'muj-olx.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmfvXQ5kISTOpnGYhyqsJSlye7xcCn1no',
    appId: '1:488342117062:web:0755ef68d991b9986315c7',
    messagingSenderId: '488342117062',
    projectId: 'muj-olx',
    authDomain: 'muj-olx.firebaseapp.com',
    storageBucket: 'muj-olx.appspot.com',
  );
}
